#!/usr/bin/env bash

VPN_IP=$(ip -4 addr show tun0 2>/dev/null | grep -oP '(?<=inet\s)\d+(.\d+){3}')

if [ -n "$VPN_IP" ]; then
echo " $VPN_IP"
else
LAN_IP=$(hostname -I | awk '{print $1}')
echo " $LAN_IP"
fi

